CREATE SEQUENCE GEN_LEADID;
CREATE SEQUENCE GEN_LEAD_ACTID;
CREATE SEQUENCE GEN_USERID;

SET GENERATOR GEN_LEADID TO 87;
SET GENERATOR GEN_LEAD_ACTID TO 348;
SET GENERATOR GEN_USERID TO 32;

CREATE TABLE USERS
(
  USERID varchar(10) NOT NULL,
  EMAIL varchar(120) NOT NULL,
  PASSWORDHASH varchar(150),
  SYSTEMROLE varchar(10),
  ISACTIVE boolean DEFAULT TRUE,
  LASTLOGIN timestamp,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  COMPANY varchar(80),
  ALIAS varchar(50),
  POSTCODE varchar(10) NOT NULL,
  CITY varchar(100) NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (USERID),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE LEAD
(
  LEADID integer NOT NULL,
  PRODUCTID varchar(100),
  COMPANYNAME varchar(80),
  CONTACTNAME varchar(100),
  CONTACTNO varchar(15),
  EMAIL varchar(120),
  ADDRESS1 varchar(80),
  ADDRESS2 varchar(80),
  CITY varchar(40),
  POSTCODE varchar(5),
  BUSINESSNATURE varchar(50),
  USERCOUNT integer,
  EXISTINGSOFTWARE varchar(40),
  DEMOMODE varchar(10),
  DESCRIPTION varchar(500),
  REFERRALCODE varchar(20),
  CREATEDAT timestamp DEFAULT CURRENT_TIMESTAMP,
  CREATEDBY varchar(30),
  ASSIGNEDTO varchar(10),
  LASTMODIFIED timestamp,
  COUNTRY varchar(100),
  STATE varchar(100),
  ISDELETED boolean DEFAULT FALSE,
  CONSTRAINT PK_LEAD PRIMARY KEY (LEADID)
);

CREATE TABLE LEAD_ACT
(
  LEAD_ACTID integer NOT NULL,
  LEADID integer NOT NULL,
  USERID varchar(10) NOT NULL,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  SUBJECT varchar(50),
  DESCRIPTION varchar(1000),
  STATUS varchar(15),
  DEALTPRODUCT varchar(100),
  SERIALACC varchar(20),
  SERIALPAY varchar(20),
  CONSTRAINT PK_LEAD_ACT PRIMARY KEY (LEAD_ACTID)
);

CREATE TABLE REFERRER_PAYOUT
(
  REFERRERPAYOUTID integer NOT NULL,
  DEALSUBMISSIONID integer,
  USERID varchar(10),
  STATUS varchar(25),
  REFERRERID varchar(10),
  DATEGENERATED timestamp DEFAULT CURRENT_TIMESTAMP,
  DATEPAID timestamp,
  CONSTRAINT PK_REFERRER_PAYOUT PRIMARY KEY (REFERRERPAYOUTID)
);

CREATE TABLE USER_PASSKEY
(
  USER_PASSKEYID bigint NOT NULL,
  USERID varchar(10) NOT NULL,
  NICKNAME varchar(40),
  CREDENTIAL blob sub_type 0,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_USER_PASSKEY PRIMARY KEY (USER_PASSKEYID)
);

CREATE TABLE "migrations"
(
  "id" integer NOT NULL,
  "migration" varchar(255) NOT NULL,
  "batch" integer NOT NULL
);



GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON USERS TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON LEAD TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON LEAD_ACT TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON REFERRER_PAYOUT TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON USER_PASSKEY TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON "migrations" TO SYSDBA WITH GRANT OPTION;

CREATE TABLE ATTACHMENT
(
  SHA1 varchar(40) NOT NULL,
  CONTENT blob sub_type 0,
  CONSTRAINT PK_ATTACHMENT PRIMARY KEY (SHA1)
);

CREATE TABLE LEAD_ACT_ATTACHMENT
(
  LEAD_ACTID integer NOT NULL,
  SHA1 varchar(40) NOT NULL,
  CONSTRAINT PK_LEAD_ACT_ATTACHMENT PRIMARY KEY (LEAD_ACTID, SHA1)
);



GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON ATTACHMENT TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON LEAD_ACT_ATTACHMENT TO SYSDBA WITH GRANT OPTION;


-- Performance Indexes from Migration (2026_04_06_000001)
CREATE INDEX idx_lead_assignedTo ON LEAD(ASSIGNEDTO);
CREATE INDEX idx_lead_currentstatus ON LEAD(CURRENTSTATUS);
CREATE INDEX idx_lead_createdat ON LEAD(CREATEDAT);
CREATE INDEX idx_lead_lastmodified ON LEAD(LASTMODIFIED);
CREATE INDEX idx_lead_assigned_status ON LEAD(ASSIGNEDTO, CURRENTSTATUS);

CREATE INDEX idx_lead_act_leadid ON LEAD_ACT(LEADID);
CREATE INDEX idx_lead_act_userid ON LEAD_ACT(USERID);
CREATE INDEX idx_lead_act_status ON LEAD_ACT(STATUS);
CREATE INDEX idx_lead_act_creationdate ON LEAD_ACT(CREATIONDATE);
CREATE INDEX idx_lead_act_status_date ON LEAD_ACT(STATUS, CREATIONDATE);

CREATE INDEX idx_users_userid ON USERS(USERID);
CREATE INDEX idx_users_systemrole ON USERS(SYSTEMROLE);
CREATE INDEX idx_users_isactive ON USERS(ISACTIVE);
CREATE INDEX idx_users_role_active ON USERS(SYSTEMROLE, ISACTIVE);

CREATE INDEX idx_referrer_payout_userid ON REFERRER_PAYOUT(USERID);
CREATE INDEX idx_referrer_payout_dategenerated ON REFERRER_PAYOUT(DATEGENERATED);
CREATE INDEX idx_referrer_payout_status ON REFERRER_PAYOUT(STATUS);
  
CREATE SEQUENCE GEN_MIGRATIONS_ID;
SET TERM ^ ;
CREATE TRIGGER TRG_MIGRATIONS_BI FOR "migrations"
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW."id" IS NULL) THEN
    NEW."id" = NEXT VALUE FOR GEN_MIGRATIONS_ID;
END^
SET TERM ; ^
