CREATE SEQUENCE GEN_LEADID;
CREATE SEQUENCE GEN_LEAD_ACTID;
CREATE SEQUENCE GEN_USERID;

SET GENERATOR GEN_LEADID TO 87;
SET GENERATOR GEN_LEAD_ACTID TO 348;
SET GENERATOR GEN_USERID TO 32;

CREATE TABLE USERS
(
  USERID varchar(10) NOT NULL,
  EMAIL varchar(120) NOT NULL,
  PASSWORDHASH varchar(150),
  SYSTEMROLE varchar(10),
  ISACTIVE boolean DEFAULT TRUE,
  LASTLOGIN timestamp,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  COMPANY varchar(80),
  ALIAS varchar(50),
  POSTCODE varchar(10) NOT NULL,
  CITY varchar(100) NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (USERID),
  CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CHK_USERS_SYSTEMROLE
    CHECK (SYSTEMROLE IN ('Dealer', 'Manager', 'Admin'))
);

CREATE TABLE LEAD
(
  LEADID integer NOT NULL,
  PRODUCTID varchar(100),
  COMPANYNAME varchar(80),
  CONTACTNAME varchar(100),
  CONTACTNO varchar(15),
  EMAIL varchar(120),
  ADDRESS1 varchar(80),
  ADDRESS2 varchar(80),
  CITY varchar(40),
  POSTCODE varchar(5),
  BUSINESSNATURE varchar(50),
  USERCOUNT integer,
  EXISTINGSOFTWARE varchar(40),
  DEMOMODE varchar(10),
  DESCRIPTION varchar(500),
  REFERRALCODE varchar(20),
  CREATEDAT timestamp DEFAULT CURRENT_TIMESTAMP,
  CREATEDBY varchar(30),
  ASSIGNEDTO varchar(10),
  LASTMODIFIED timestamp,
  COUNTRY varchar(100),
  STATE varchar(100),
  ISDELETED boolean DEFAULT FALSE,
  CONSTRAINT PK_LEAD PRIMARY KEY (LEADID),
  CONSTRAINT CHK_LEAD_DEMOMODE
    CHECK (DEMOMODE IN ('Zoom', 'On-site'))
);

CREATE TABLE LEAD_ACT
(
  LEAD_ACTID integer NOT NULL,
  LEADID integer NOT NULL,
  USERID varchar(10) NOT NULL,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  SUBJECT varchar(50),
  DESCRIPTION varchar(1000),
  ATTACHMENT blob sub_type 0,
  STATUS varchar(15),
  DEALTPRODUCT varchar(100),
  ATTACHMENT2 blob sub_type 0,
  SERIALACC varchar(20),
  SERIALPAY varchar(20),
  CONSTRAINT PK_LEAD_ACT PRIMARY KEY (LEAD_ACTID),
  CONSTRAINT CHK_LEAD_ACT_STATUS
    CHECK (STATUS IN ('Created','Pending','FollowUp','Demo','Confirmed','Completed','Rewarded','Failed','Cancelled'))
);

CREATE TABLE REFERRER_PAYOUT
(
  REFERRERPAYOUTID integer NOT NULL,
  DEALSUBMISSIONID integer,
  USERID varchar(10),
  STATUS varchar(25),
  REFERRERID varchar(10),
  DATEGENERATED timestamp DEFAULT CURRENT_TIMESTAMP,
  DATEPAID timestamp,
  CONSTRAINT PK_REFERRER_PAYOUT PRIMARY KEY (REFERRERPAYOUTID),
  CONSTRAINT CHK_REFERRER_PAYOUT_STATUS
    CHECK (STATUS IN ('Awaiting Deal Completion', 'Pending', 'Paid'))
);

CREATE TABLE USER_PASSKEY
(
  USER_PASSKEYID bigint NOT NULL,
  USERID varchar(10) NOT NULL,
  NICKNAME varchar(40),
  CREDENTIAL blob sub_type 0,
  CREATIONDATE timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_USER_PASSKEY PRIMARY KEY (USER_PASSKEYID)
);

CREATE TABLE "migrations"
(
  "id" integer NOT NULL,
  "migration" varchar(255) NOT NULL,
  "batch" integer NOT NULL
);

ALTER TABLE LEAD
  ADD CONSTRAINT FK_LEAD_ASSIGNED
  FOREIGN KEY (ASSIGNEDTO) REFERENCES USERS (USERID);

ALTER TABLE LEAD_ACT
  ADD CONSTRAINT FK_LEAD_ACT_USER
  FOREIGN KEY (USERID) REFERENCES USERS (USERID);

ALTER TABLE LEAD_ACT
  ADD CONSTRAINT FK_LEAD_ACT_LEAD
  FOREIGN KEY (LEADID) REFERENCES LEAD (LEADID) ON DELETE CASCADE;

ALTER TABLE REFERRER_PAYOUT
  ADD CONSTRAINT FK_PAYOUT_REFERRER
  FOREIGN KEY (REFERRERID) REFERENCES USERS (USERID);

ALTER TABLE REFERRER_PAYOUT
  ADD CONSTRAINT FK_PAYOUT_USER
  FOREIGN KEY (USERID) REFERENCES USERS (USERID);

ALTER TABLE USER_PASSKEY
  ADD CONSTRAINT FK_PASSKEY_USER
  FOREIGN KEY (USERID) REFERENCES USERS (USERID);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON USERS TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON LEAD TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON LEAD_ACT TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON REFERRER_PAYOUT TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON USER_PASSKEY TO SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
ON "migrations" TO SYSDBA WITH GRANT OPTION;


